### ISSUE TITLE
xcconfig not found

### ISSUE THREAD

**Issue by mickeyl** [stacksift/Impact#5]
Trying to build it, but "xcconfigs/UniversalFramework_Framework.xcconfig" doesn't seem to be checked into the source tree.

**Comment by mattmassicotte** [comment]
Yes, sorry the building instructions aren't more clear. You must initialize git submodules prior to building from Xcode with:

    git submodule update --init

**Comment by mickeyl** [comment]
Ah, of course. Thanks
